name: Deploy to Main

on:
  push:
    branches:
      - main

jobs:
  deploy_prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Debug
        run: |
          pwd
          ls
      

      - name: Run Script
        run: bash PROJECT/script_for_be.sh
