name: Deploy to Development

on:
  push:
    branches:
      - main

jobs:
    deploy_prod:
      runs-on: ubuntu-latest
      steps:
        - run: "bash /home/ubuntu/PROJECT/script_for_be.sh"
        
